In [35]:
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns

In [37]:
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score

milk = pd.read_csv("C:/Users\dai\Desktop\Machine Learning\Datasets\milk.csv",index_col=0)


scaler = StandardScaler().set_output(transform='pandas')
milkscaled = scaler.fit_transform(milk)


clust_DB = DBSCAN(eps=1,min_samples=2)
clust_DB.fit(milkscaled)

print(clust_DB.labels_)

[ 0  0  0  0  0  0  0  0  0 -1  0  0  0  0  0  0  1 -1 -1  1  2  2  2 -1
 -1]

In [39]:
clust_milk = milk.copy()
clust_milk['Clust'] = clust_DB.labels_
clust_milk.sort_values(by='Clust')

print(clust_milk.groupby('Clust').mean())
print(clust_milk.sort_values(by='Clust').head())

           water    protein        fat   lactose    ash
Clust
-1     62.980000   9.260000  22.780000  2.560000  1.012
 0     86.360000   3.886667   4.033333  5.166667  0.628
 1     74.400000   9.250000  11.050000  3.150000  1.300
 2     65.166667  10.733333  20.400000  2.233333  1.500
          water  protein   fat  lactose   ash  Clust
Animal
DOLPHIN    44.9     10.6  34.9      0.9  0.53     -1
RABBIT     71.3     12.3  13.1      1.9  2.30     -1
ELEPHANT   70.7      3.6  17.6      5.6  0.63     -1
SEAL       46.4      9.7  42.0      0.0  0.85     -1
CAT        81.6     10.1   6.3      4.4  0.75     -1

In [40]:

milkscaled['Clust'] = clust_DB.labels_
milk_scl_inliers = milkscaled[milkscaled['Clust']!=-1]
print( silhouette_score(milk_scl_inliers.iloc[:,:-1],
                 milk_scl_inliers.iloc[:,-1]) )

eps_range = [0.2,0.4,0.6,1]
mp_range = [2,3,4,5]
cnt = 0
a =[]
for i in eps_range:
    for j in mp_range:
        clust_DB = DBSCAN(eps=i, min_samples=j)
        clust_DB.fit(milkscaled.iloc[:,:5])
        if len(set(clust_DB.labels_)) > 2:
            cnt = cnt + 1
            milkscaled['Clust'] = clust_DB.labels_
            milk_scl_inliers = milkscaled[milkscaled['Clust']!=-1]
            sil_sc = silhouette_score(milk_scl_inliers.iloc[:,:-1],
                             milk_scl_inliers.iloc[:,-1])
            a.append([cnt,i,j,sil_sc])
            print(i,j,sil_sc)
    
a = np.array(a)
pa = pd.DataFrame(a,columns=['Sr','eps','min_pt','sil'])
print("Best Paramters:")
pa[pa['sil'] == pa['sil'].max()]

### Labels with best parameters
clust_DB = DBSCAN(eps=0.4, min_samples=2)
clust_DB.fit(milkscaled.iloc[:,:5])
print(clust_DB.labels_)

clust_milk = milk.copy()
clust_milk["Clust"] = clust_DB.labels_
clust_milk.sort_values(by='Clust')


clust_milk.groupby('Clust').mean()
clust_milk.sort_values('Clust')

0.4344818095328392
0.4 2 0.6518937593821538
0.4 3 0.5385180352469559
0.6 2 0.5934459505692155
0.6 3 0.5344431042454363
0.6 4 0.5519747727201489
1 2 0.4344818095328392
1 3 0.6473871775367226
Best Paramters:
[-1  0  0 -1 -1  1  1  2 -1 -1  2  1 -1 -1  1  2 -1 -1 -1 -1  3  3 -1 -1
 -1]

            water  protein   fat  lactose   ash  Clust
Animal
HORSE        90.1      2.6   1.0      6.9  0.35     -1
WHALE        64.8     11.1  21.2      1.6  1.70     -1
RAT          72.5      9.2  12.6      3.3  1.40     -1
RABBIT       71.3     12.3  13.1      1.9  2.30     -1
ELEPHANT     70.7      3.6  17.6      5.6  0.63     -1
DOG          76.3      9.3   9.5      3.0  1.20     -1
PIG          82.8      7.1   5.1      3.7  1.10     -1
SEAL         46.4      9.7  42.0      0.0  0.85     -1
CAT          81.6     10.1   6.3      4.4  0.75     -1
MULE         90.0      2.0   1.8      5.5  0.47     -1
HIPPO        90.4      0.6   4.5      4.4  0.10     -1
DONKEY       90.3      1.7   1.4      6.2  0.40     -1
GUINEA PIG   81.9      7.4   7.2      2.7  0.85     -1
DOLPHIN      44.9     10.6  34.9      0.9  0.53     -1
MONKEY       88.4      2.2   2.7      6.4  0.18      0
ORANGUTAN    88.5      1.4   3.5      6.0  0.24      0
LLAMA        86.5      3.9   3.2      5.6  0.80      1
BISON        86.9      4.8   1.7      5.7  0.90      1
ZEBRA        86.2      3.0   4.8      5.3  0.70      1
CAMEL        87.7      3.5   3.4      4.8  0.71      1
FOX          81.6      6.6   5.9      4.9  0.93      2
BUFFALO      82.1      5.9   7.9      4.7  0.78      2
SHEEP        82.0      5.6   6.4      4.7  0.91      2
DEER         65.9     10.4  19.7      2.6  1.40      3
REINDEER     64.8     10.7  20.3      2.5  1.40      3

In [41]:
from sklearn.cluster import DBSCAN
import numpy as np
from sklearn.metrics import silhouette_score
import pandas as pd

milk = pd.read_csv(r"C:\Users\dai\Desktop\Machine Learning\Datasets\nutrient.csv",index_col=0)

from sklearn.preprocessing import StandardScaler
# Create scaler: scaler
scaler = StandardScaler().set_output(transform='pandas')
milkscaled=scaler.fit_transform(milk)

clust_DB = DBSCAN(eps=1, min_samples=2)
clust_DB.fit(milkscaled)
print(clust_DB.labels_)

clust_milk = milk.copy()
clust_milk["Clust"] = clust_DB.labels_
clust_milk.sort_values(by='Clust')

clust_milk.groupby('Clust').mean()
clust_milk.sort_values('Clust')


milkscaled['Clust'] = clust_DB.labels_
milk_scl_inliers = milkscaled[milkscaled['Clust']!=-1]
print( silhouette_score(milk_scl_inliers.iloc[:,:-1],
                 milk_scl_inliers.iloc[:,-1]) )

eps_range = [0.2,0.4,0.6,1]
mp_range = [2,3,4,5]
cnt = 0
a =[]
for i in eps_range:
    for j in mp_range:
        clust_DB = DBSCAN(eps=i, min_samples=j)
        clust_DB.fit(milkscaled.iloc[:,:5])
        if len(set(clust_DB.labels_)) > 2:
            cnt = cnt + 1
            milkscaled['Clust'] = clust_DB.labels_
            milk_scl_inliers = milkscaled[milkscaled['Clust']!=-1]
            sil_sc = silhouette_score(milk_scl_inliers.iloc[:,:-1],
                             milk_scl_inliers.iloc[:,-1])
            a.append([cnt,i,j,sil_sc])
            print(i,j,sil_sc)
    
a = np.array(a)
pa = pd.DataFrame(a,columns=['Sr','eps','min_pt','sil'])
print("Best Paramters:")
pa[pa['sil'] == pa['sil'].max()]

### Labels with best parameters
clust_DB = DBSCAN(eps=0.4, min_samples=2)
clust_DB.fit(milkscaled.iloc[:,:5])
print(clust_DB.labels_)

clust_milk = milk.copy()
clust_milk["Clust"] = clust_DB.labels_
clust_milk.sort_values(by='Clust')


clust_milk.groupby('Clust').mean()
clust_milk.sort_values('Clust')

[ 0  0 -1  0  1  1  1 -1  0  0  0  0  0  0  1  1 -1 -1  2  2  2  3  2  3
 -1  1 -1]
0.43236957939711584
0.2 2 0.5710837307456915
0.4 2 0.9040570858308878
0.6 2 0.7752441663222646
1 2 0.43236957939711584
1 3 0.43147150560271585
Best Paramters:
[ 0 -1 -1  0 -1 -1  1 -1 -1 -1  0  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1  1 -1]

                     energy  protein  fat  calcium  iron  Clust
Food_Item
BEEF TONGUE             205       18   14        7   2.5     -1
SARDINES CANNED         180       22    9      367   2.5     -1
SALMON CANNED           120       17    5      159   0.7     -1
PERCH FRIED             195       16   11       14   1.3     -1
MACKEREL CANNED         155       16    9      157   1.8     -1
MACKEREL BROILED        200       19   13        5   1.0     -1
HADDOCK FRIED           135       16    5       15   0.5     -1
CRABMEAT CANNED          90       14    2       38   0.8     -1
CLAMS CANNED             45        7    1       74   5.4     -1
CLAMS RAW                70       11    1       82   6.0     -1
BLUEFISH BAKED          135       22    4       25   0.6     -1
VEAL CUTLET             185       23    9        9   2.7     -1
SHRIMP CANNED           110       23    1       98   2.6     -1
LAMB SHOULDER ROAST     300       18   25        9   2.3     -1
LAMB LEG ROAST          265       20   20        9   2.6     -1
BEEF HEART              160       26    5       14   5.9     -1
CHICKEN BROILED         115       20    3        8   1.4     -1
BEEF CANNED             180       22   10       17   3.7     -1
BEEF ROAST              420       15   39        7   2.0     -1
HAMBURGER               245       21   17        9   2.7     -1
PORK ROAST              340       19   29        9   2.5      0
SMOKED HAM              340       20   28        9   2.5      0
BEEF STEAK              375       19   32        9   2.6      0
PORK SIMMERED           355       19   30        9   2.4      0
BEEF BRAISED            340       20   28        9   2.6      0
TUNA CANNED             170       25    7        7   1.2      1
CHICKEN CANNED          170       25    7       12   1.5      1

In [45]:
from sklearn.cluster import DBSCAN
import numpy as np
from sklearn.metrics import silhouette_score
import pandas as pd

milk = pd.read_csv(r"C:/Users\dai\Desktop\Machine Learning\Cases\Cases\Recency Frequency Monetary\rfm_data_customer.csv",index_col=0)
milk.drop('most_recent_visit',axis=1,inplace=True)
from sklearn.preprocessing import StandardScaler
# Create scaler: scaler
scaler = StandardScaler().set_output(transform='pandas')
milkscaled=scaler.fit_transform(milk)

clust_DB = DBSCAN(eps=1, min_samples=2)
clust_DB.fit(milkscaled)
print(clust_DB.labels_)

clust_milk = milk.copy()
clust_milk["Clust"] = clust_DB.labels_
clust_milk.sort_values(by='Clust')

clust_milk.groupby('Clust').mean()
clust_milk.sort_values('Clust')

eps_range = [0.6,1,1.5,2]
mp_range = [20,50,100]
cnt = 0
a =[]
for i in eps_range:
    for j in mp_range:
        clust_DB = DBSCAN(eps=i, min_samples=j)
        clust_DB.fit(milkscaled.iloc[:,:5])
        if len(set(clust_DB.labels_)) > 2:
            cnt = cnt + 1
            milkscaled['Clust'] = clust_DB.labels_
            milk_scl_inliers = milkscaled[milkscaled['Clust']!=-1]
            sil_sc = silhouette_score(milk_scl_inliers.iloc[:,:-1],
                             milk_scl_inliers.iloc[:,-1])
            a.append([cnt,i,j,sil_sc])
            print(i,j,sil_sc)
    
a = np.array(a)
pa = pd.DataFrame(a,columns=['Sr','eps','min_pt','sil'])
print("Best Paramters:")
pa[pa['sil'] == pa['sil'].max()]

### Labels with best parameters
clust_DB = DBSCAN(eps=0.4, min_samples=2)
clust_DB.fit(milkscaled.iloc[:,:5])
print(clust_DB.labels_)

clust_milk = milk.copy()
clust_milk["Clust"] = clust_DB.labels_
clust_milk.sort_values(by='Clust')


clust_milk.groupby('Clust').mean()
clust_milk.sort_values('Clust')

[0 0 0 ... 0 0 0]

ValueError: Shape of passed values is (0, 1), indices imply (0, 4)